Feat/deepchecks
credo-ai/credoai_lens pull request #220
Opened 2022-10-27 23:42 UTC by esherman-credo

## Change description

Implement deepchecks evaluator and evidence +container types. By default, runs a subset of the deepchecks `model_evaluation` Suite. Capable of accepting, as input, any list of Checks objects, including checks with passing conditions specified.

`get_results()` and `get_evidence()` currently have incongruous designs. `get_results()` returns a deepchecks `SuiteResult` object which can be printed to provide the standard deepchecks interactive graphic with failed, passed, other, and not-run checks. `get_evidence()` returns a `TableEvidence` object with an underlying dataframe consisting of two columns: the name of the check, and the results (pass, fail, etc.); switching this to return `DeepchecksEvidence` (already implemented) is trivial.

Re: merge conflict/tests -- many changes were pushed to develop between the time this branch was created and now. We will need to do some serious manual merging!

## Type of change
- [ X] New feature (adds functionality)

### Development

- [ X] Application changes have been tested thoroughly

2022-10-31 23:45 UTC, IanAtCredo commented on credoai/evaluators/deepchecks.py
> +                    self.suite.run(
Though it is simple to write `self.suite.run`, there's slightly more in `evaluate` than I'd like to see. A separate function called `run_suite` would be better, and then evaluate takes the output of that and just wraps it into a `DeepchecksContainer`

2022-10-31 23:46 UTC, IanAtCredo commented on credoai/evidence/containers.py
> +            raise ValidationError("'df' must be a dataframe")
```suggestion
            raise ValidationError("'data' must be a dataframe")
```

2022-10-31 23:46 UTC, IanAtCredo commented on credoai/evidence/containers.py
> +        data : pd.DataFrame
No always a dataframe now. Documentation should change.

2022-10-31 23:47 UTC, IanAtCredo commented on credoai/evidence/containers.py
> +    def __init__(self, df, labels: dict = None, metadata: dict = None):
Why did you change this to df?

2022-10-31 23:49 UTC, IanAtCredo requested changes
Minor changes requested, along with the conflicts. Very easy to read and integrate, which was what i hoped.

I'll actually run it once those changes are made and the conflicts resolved.

2022-11-02 21:29 UTC, IanAtCredo approved these changes

2022-11-02 23:33 UTC, IanAtCredo approved these changes
Not able to see the widget - any understanding of what may be causing this? Otherwise lg.

<img width="1517" alt="image" src="https://user-images.githubusercontent.com/85892367/199621690-f8e5bcbe-ef18-42d7-8699-d2424308d6ca.png">

2022-11-03 00:12 UTC, esherman-credo commented
You're indexing differently from how I'd expect. Shouldn't `get_results()` return a dictionary?

From there you're using `results` whereas I thought this should be an auto-generated name with the evaluator name and a UUID. For instance, in my local notebook, I have to print to check first and see that the suffix is the UUID d4d0cc:

![image](https://user-images.githubusercontent.com/114082449/199625125-6619495b-082f-4129-b4e5-f9ee33e0bb19.png)

2022-11-03 00:17 UTC, esherman-credo commented
Update: needed to git pull locally to merge with changes to the Evaluator naming.

Now I get the right thing:
![image](https://user-images.githubusercontent.com/114082449/199625760-67a3d00d-4c3c-4898-bb9d-28a38d5547a2.png)


I suspect it's something like you don't have ipywidgets installed?

2022-11-04 22:13 UTC, merged