Docs/list metrics
credo-ai/credoai_lens pull request #234
Opened 2022-11-03 17:16 UTC by esherman-credo

## Change description

Modify https://credoai-lens.readthedocs.io/en/latest/metrics.html# to support call to `list_metrics` so all supported metrics can be displayed.

NOTE: I TESTED THIS "LOCALLY" IN A VSCODE RENDER OF THE HTML. I DO NOT KNOW HOW TO TEST ON READTHEDOCS WITHOUT MERGING TO DEVELOP BRANCH.

## Type of change
- [X ] New feature (adds functionality)

2022-11-03 23:59 UTC, fabrizio-credo requested changes
So I activated your version on read the docs, and tested the build. It failed, you can check the log here: 

https://readthedocs.org/projects/credoai-lens/builds/18532017/

It seems to be an issue due to import of numpy... not sure what the reason is.

MInor issue: The local html creation works fine, there are a bunch of non critical errors, somehow it tries to import ProfilerEvidence and DataProfiling, which doesn't exist anymore.
Not sure if this is critical, can you reproduce this?

![image](https://user-images.githubusercontent.com/110419923/199856963-e7c1e844-146e-4a27-84ab-7fff4811a5db.png)

2022-11-04 02:13 UTC, esherman-credo commented
I don't get those warnings/errors exactly. I get _a lot_ of them. And this import part looks like it's trying to import those evaluators.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/114082449/199869224-965ef4dc-1751-4ce4-93be-da09c5f9ec65.png">

I just looked in develop and I still see data_profiler so I'm not sure what you're referring to?


Re numpy: I suspect that's an error because numpy is imported in metric_utils (which is where `list_metrics()` is defined). I'll add that and we'll see!

2022-11-04 17:37 UTC, esherman-credo commented
Alright, after some help activating the RTD page for this branch from @fabrizio-credo, we're good to go:

https://credoai-lens.readthedocs.io/en/docs-list_metrics/metrics.html

2022-11-04 17:37 UTC, fabrizio-credo approved these changes

2022-11-04 17:38 UTC, merged