Docs/update governance notebook
credo-ai/credoai_lens pull request #236
Opened 2022-11-07 18:48 UTC by fabrizio-credo

# Modification to notebooks

- Moving run script functionality inside lens package so notebooks are runnable by a user with standard lens installation
- Update language concerning governance in the quickstarts notebooks

2022-11-08 20:22 UTC, esherman-credo requested changes

2022-11-08 23:42 UTC, fabrizio-credo commented
General question: Is there a need for tags always? Tags is a functionality, but it's not mandatory. Shouldn't the example be the most general?

2022-11-09 15:49 UTC, esherman-credo commented
Posting this screenshot of a traceback I had previously shared directly with @fabrizio-credo:

![image](https://user-images.githubusercontent.com/114082449/200874618-873b660c-096a-4296-9446-41f6a94d9982.png)


I guess tags maybe shouldn't be the default in the integration walkthrough at the top of the notebook. But it definitely needs to be mentioned somewhere in this notebook. Maybe a section at the bottom that's like "here's this optional feature we recommend"? I didn't understand the error message at first and I'm internal/aware of the point of tags.

I think the confusion comes from the fact that the traceback arises when you call `Lens.run`, which is rather detached from where the issue actually starts. The issue is caused by not specifying an optional argument (which, in this case, is not optional based on the details of other optional-but-supplied arguments) when calling the `ClassificationModel` constructor. That issue is propagated to the Lens constructor (issue propagated silently) and then doesn't pop up until we call `run()`. The `WARNING` message is helpful but probably not sufficient because most peoples' instinct is going to be to follow the actual error message.

I think it might be valuable to do this validation in the Lens constructor, since that's where the conflict arises. cc @IanAtCredo 

It might be possible to do it even earlier, at the time we wrap the model as a `ClassificationModel` (or regression model), but I'm less sure about that since the issue is caused by the intersection of the model specification and the evidence requirements coming in from Platform

2022-11-09 19:22 UTC, fabrizio-credo commented
@esherman-credo yeah I will add a section about tags in the notebook. We can revisit the issue of the error when the new connect package is redefined. As you say, this is an issue about the intersection between model config and requirements. Note: there can still be reasons to run models without tags even though there are requirements with tags, we need to keep that in mind.

2022-11-14 16:28 UTC, esherman-credo approved these changes
Please address comment but otherwise good.

2022-11-14 16:28 UTC, esherman-credo commented on docs/notebooks/platform_integration.ipynb
>      "\n",
Line 39 -> "(where do we get this?)

Either answer that question or delete (ideally the first)

2022-11-14 17:59 UTC, merged