Added confusion matrix for fairness evaluator
credo-ai/credoai_lens pull request #306
Opened 2023-01-17 23:39 UTC by fabrizio-credo

## Describe your changes
- Leveraged confusion matrix function in Performance to create a disaggregated version in Fairness.

## Issue ticket number and link

## Known outstanding issues that are not fully accounted for

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have built basic tests for new functionality (particularly new evaluators)
- [ ] If new libraries have been added, I have checked that [readthedocs](https://readthedocs.org/projects/credoai-lens/) API documentation is constructed correctly
- [ ] Will this be part of a major product update? If yes, please write one phrase about this update.

## Extra-mile Checklist
- [ ] I have thought expansively about edge cases and written tests for them

2023-01-17 23:40 UTC, fabrizio-credo commented
@IanAtCredo if there are no changes to be made, I will push the amend to the version_check file and merge.

2023-01-17 23:45 UTC, IanAtCredo requested changes
Am I missing something? I don't see how this is creating a disaggregated version. It's creating one confusion matrix over all the data. We want to create separate tables for each sensitive feature (e.g., group the y_true/y_pred and create the confusion matrices)

2023-01-17 23:48 UTC, fabrizio-credo commented
@IanAtCredo Fairness depends on sensitive feature. If we have multiple sensitive features (e.g., race and gender) these will generate different confusion matrixes. Maybe I misunderstood

2023-01-18 22:50 UTC, IanAtCredo approved these changes

2023-01-19 00:03 UTC, merged